# src/OC/PlatformBundle/Resources/config/routing.yml

# interviendra lorsque l'on voudra générer des URL
oc_platform_home:
  #path = url de la page
  # normalement on devrait mettre /platform, cependant on à changé app/config/routing.yml en rajoutant le prefix
  # {page} pour générer un système de pagination
    path:      /{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

# Redirige l'utilsateur
oc_platform_redirect:
    path:       /redirect
    defaults:
        _controller: OCPlatformBundle:Advert:redirect

oc_platform_view:
    path:      /advert/{id}
    #defaults correspond au chemin à suivre pour charger le controller et ensuite la méthode à charger au sein du controller
    defaults:
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id: \d+

oc_platform_view_slug:
    path:      /{year}/{slug}.{_format}
    defaults:
        _controller: OCPlatformBundle:Advert:viewSlug
        # Designe html comme format par défaut
        format: html

        # Requiert une suite de 4 chiffres
        requirements:
          year: \d{4}
          format: html|xml

oc_platform_add:
    path:      /add
    defaults:
        _controller: OCPlatformBundle:Advert:add

oc_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
      id: \d+
